from genson import SchemaBuilder

builder = SchemaBuilder()
# builder.add_schema({"type": "object", "properties": {}})
builder.add_object({"h_int": 5})
builder.add_object({"he_llo": {"attr_name": "toto"}})
builder.add_object({"lst_int_str": [1, "2"]})
builder.add_object({"lst_obj": [{"attr_num": 1}, {"attr_cd": "toto"}, 5]})
builder.add_object({"h_float": 4.5})
builder.add_object({"h_str": "my"})
builder.add_object({"h_bool": True})
builder.add_object({"h_null": None})
builder.add_object({"h_any": None})
builder.add_object({"h_any": "any"})
builder.add_object({"h_any": 22})
print(builder.to_json(indent=2))
sch = builder.to_schema()
